parameters:
  - name: environmentIndex
    type: string
  - name: storeSQLUser
    displayName: Store SQL Developer Accounts (Lower Envs)
    type: boolean
    default: false
  - name: permissionMsiInDb
    displayName: Permission MSIs in DBs
    type: boolean
    default: false

stages:
  - stage: AME_DEV_${{ parameters.environmentIndex }}
    dependsOn: BUILD
    variables:
    - template: ../variables-templates/dev-variables-template.yml
      parameters:
        environmentIndex: ${{ parameters.environmentIndex }}
    jobs:
      - deployment: AME_DEV
        environment: INFRASTRUCTURE_NPD
        pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
      - template: ../deployment-templates/infrastructure-deployment-jobs-template.yml
        parameters:
          pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
          azureSubscription: AzureRM_US_AUDIT_PREPROD
          geo: ame
          lifecycle: npd
          environment: dev
          environmentIndex: ${{ parameters.environmentIndex }}
          storeSQLUser: ${{ parameters.storeSQLUser }}
          permissionMsiInDb: ${{ parameters.permissionMsiInDb }}

  - stage: AME_QA_${{ parameters.environmentIndex }}
    dependsOn: AME_DEV_${{ parameters.environmentIndex }}
    variables:
    - template: ../variables-templates/qa-variables-template.yml
      parameters:
        environmentIndex: ${{ parameters.environmentIndex }}
    jobs:
      - deployment: AME_QA
        environment: INFRASTRUCTURE_NPD
        pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
      - template: ../deployment-templates/infrastructure-deployment-jobs-template.yml
        parameters:
          pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
          azureSubscription: AzureRM_US_AUDIT_PREPROD
          geo: ame
          lifecycle: npd
          environment: qa
          environmentIndex: ${{ parameters.environmentIndex }}
          storeSQLUser: ${{ parameters.storeSQLUser }}
          permissionMsiInDb: ${{ parameters.permissionMsiInDb }}

  - stage: EMA_DEV_${{ parameters.environmentIndex }}
    dependsOn: BUILD
    variables:
    - template: ../variables-templates/dev-variables-template.yml
      parameters:
        environmentIndex: ${{ parameters.environmentIndex }}
    jobs:
      - deployment: EMA_DEV
        environment: INFRASTRUCTURE_NPD
        pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
      - template: ../deployment-templates/infrastructure-deployment-jobs-template.yml
        parameters:
          pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
          azureSubscription: AzureRM_EMA_AUDIT_PREPROD
          azureSubscriptionSqlReplica: ARM_Navigator_EMA_Deploy_NonProd
          geo: ema
          lifecycle: npd
          environment: dev
          environmentIndex: ${{ parameters.environmentIndex }}
          isPrimaryGeo: true
          sqlReplicas:
            - use2
            - jpe
          storeSQLUser: ${{ parameters.storeSQLUser }}
          permissionMsiInDb: ${{ parameters.permissionMsiInDb }}

  - stage: EMA_QA_${{ parameters.environmentIndex }}
    dependsOn: EMA_DEV_${{ parameters.environmentIndex }}
    variables:
    - template: ../variables-templates/qa-variables-template.yml
      parameters:
        environmentIndex: ${{ parameters.environmentIndex }}
    jobs:
      - deployment: EMA_QA
        environment: INFRASTRUCTURE_NPD
        pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
      - template: ../deployment-templates/infrastructure-deployment-jobs-template.yml
        parameters:
          pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
          azureSubscription: AzureRM_EMA_AUDIT_PREPROD
          azureSubscriptionSqlReplica: ARM_Navigator_EMA_Deploy_NonProd
          geo: ema
          lifecycle: npd
          environment: qa
          environmentIndex: ${{ parameters.environmentIndex }}
          isPrimaryGeo: true
          sqlReplicas:
            - use2
            - jpe
          storeSQLUser: ${{ parameters.storeSQLUser }}
          permissionMsiInDb: ${{ parameters.permissionMsiInDb }}

  - stage: APA_DEV_${{ parameters.environmentIndex }}
    dependsOn: BUILD
    variables:
    - template: ../variables-templates/dev-variables-template.yml
      parameters:
        environmentIndex: ${{ parameters.environmentIndex }}
    jobs:
      - deployment: APA_DEV
        environment: INFRASTRUCTURE_NPD
        pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
      - template: ../deployment-templates/infrastructure-deployment-jobs-template.yml
        parameters:
          pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
          azureSubscription: AzureRM_APA_AUDIT_PREPROD
          geo: apa
          lifecycle: npd
          environment: dev
          environmentIndex: ${{ parameters.environmentIndex }}
          storeSQLUser: ${{ parameters.storeSQLUser }}
          permissionMsiInDb: ${{ parameters.permissionMsiInDb }}

  - stage: APA_QA_${{ parameters.environmentIndex }}
    dependsOn: APA_DEV_${{ parameters.environmentIndex }}
    variables:
    - template: ../variables-templates/qa-variables-template.yml
      parameters:
        environmentIndex: ${{ parameters.environmentIndex }}
    jobs:
      - deployment: APA_QA
        environment: INFRASTRUCTURE_NPD
        pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
      - template: ../deployment-templates/infrastructure-deployment-jobs-template.yml
        parameters:
          pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
          azureSubscription: AzureRM_APA_AUDIT_PREPROD
          geo: apa
          lifecycle: npd
          environment: qa
          environmentIndex: ${{ parameters.environmentIndex }}
          storeSQLUser: ${{ parameters.storeSQLUser }}
          permissionMsiInDb: ${{ parameters.permissionMsiInDb }}
