stages:
- stage: AME_VAL
  dependsOn: BUILD
  variables:
    - template: ../variables-templates/val-variables-template.yml
  jobs:
    - deployment: AME_VAL
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
    - template: ../deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PROD
        geo: ame
        lifecycle: stg
        environment: val
        
- stage: AME_PROD
  dependsOn: AME_VAL
  variables:
    - template: ../variables-templates/prod-variables-template.yml
  jobs:
    - deployment: AME_PROD
      environment: INFRASTRUCTURE_PROD_AME
      pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
    - template: ../deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PROD
        geo: ame
        lifecycle: prod
        environment: prod

- stage: AME_BCP
  dependsOn: AME_PROD
  variables:
    - template: ../variables-templates/bcp-variables-template.yml
  jobs:
    - deployment: AME_BCP
      environment: INFRASTRUCTURE_PROD_AME
      pool: ASSURANCE-USC-BCP-AKS-WIN-RELEASE
    - template: ../deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USC-BCP-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PROD
        geo: ame
        lifecycle: bcp
        environment: bcp

- stage: EMA_VAL
  dependsOn: BUILD
  variables:
    - template: ../variables-templates/val-variables-template.yml
  jobs:
    - deployment: EMA_VAL
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
    - template: ../deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PROD
        geo: ema
        lifecycle: stg
        environment: val
        isPrimaryGeo: true

- stage: EMA_PROD
  dependsOn: EMA_VAL
  variables:
    - template: ../variables-templates/prod-variables-template.yml
  jobs:
    - deployment: EMA_PROD
      environment: INFRASTRUCTURE_PROD_EMA
      pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
    - template: ../deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PROD
        geo: ema
        lifecycle: prod
        environment: prod
        isPrimaryGeo: true

- stage: EMA_BCP
  dependsOn: EMA_PROD
  variables:
    - template: ../variables-templates/bcp-variables-template.yml
  jobs:
    - deployment: EMA_BCP
      environment: INFRASTRUCTURE_PROD_EMA
      pool: ASSURANCE-EUN-BCP-AKS-WIN-RELEASE
    - template: ../deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUN-BCP-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PROD
        geo: ema
        lifecycle: bcp
        environment: bcp  
        isPrimaryGeo: true
        
- stage: APA_VAL
  dependsOn: BUILD
  variables:
    - template: ../variables-templates/val-variables-template.yml
  jobs:
    - deployment: APA_VAL
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
    - template: ../deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PROD
        geo: apa
        lifecycle: stg
        environment: val

- stage: APA_PROD
  dependsOn: APA_VAL
  variables:
    - template: ../variables-templates/prod-variables-template.yml
  jobs:
    - deployment: APA_PROD
      environment: INFRASTRUCTURE_PROD_APA
      pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
    - template: ../deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PROD
        geo: apa
        lifecycle: prod
        environment: prod

- stage: APA_BCP
  dependsOn: APA_PROD
  variables:
    - template: ../variables-templates/bcp-variables-template.yml
  jobs:
    - deployment: APA_BCP
      environment: INFRASTRUCTURE_PROD_APA
      pool: ASSURANCE-JPW-BCP-AKS-WIN-RELEASE
    - template: ../deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPW-BCP-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PROD
        geo: apa
        lifecycle: bcp
        environment: bcp