stages:
  - stage: AME_VAL
    dependsOn: BUILD
    jobs:
      - deployment: AME_VAL
        environment: INFRASTRUCTURE_TEAM_LEAD
        pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
      - template: ../deployment-templates/teardown-environment-jobs-template.yml
        parameters:
          pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
          azureSubscription: AzureRM_US_AUDIT_PROD
          geo: ame
          lifecycle: stg
          environment: val

  - stage: EMA_VAL
    dependsOn: BUILD
    jobs:
      - deployment: EMA_VAL
        environment: INFRASTRUCTURE_TEAM_LEAD
        pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
      - template: ../deployment-templates/teardown-environment-jobs-template.yml
        parameters:
          pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
          azureSubscription: AzureRM_EMA_AUDIT_PROD
          geo: ema
          lifecycle: stg
          environment: val

  - stage: APA_VAL
    dependsOn: BUILD
    jobs:
      - deployment: APA_VAL
        environment: INFRASTRUCTURE_TEAM_LEAD
        pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
      - template: ../deployment-templates/teardown-environment-jobs-template.yml
        parameters:
          pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
          azureSubscription: AzureRM_APA_AUDIT_PROD
          geo: apa
          lifecycle: stg
          environment: val
