parameters:
  azureSubscription: ""

steps:
  - task: AzurePowerShell@5
    displayName: 'Failover: Stop App Services - Primary'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Set-AppServiceState.ps1'
      ScriptArguments: '-ResourceGroupName $(primaryResourceGroupName) -Action "Stop"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Failover: Stop App Services - Secondary'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Set-AppServiceState.ps1'
      ScriptArguments: '-ResourceGroupName $(secondaryResourceGroupName) -Action "Stop"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Failover: Scale Up App Service Plans - Secondary'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Invoke-ScaleAppServicePlan.ps1'
      ScriptArguments: '-ResourceGroupName $(secondaryResourceGroupName) -Tier $(primaryAppServicePlanTier) -WorkerSize "Small" -ScaleUp'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Failover: Failover SQL Group'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptType: FilePath
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Invoke-SqlGroupFailover.ps1'
      ScriptArguments: '-ResourceGroupName $(secondaryResourceGroupName) -SqlServer $(secondarySqlServerName) -FailoverGroupName $(sqlFailOverGroup)'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Failover: Copy Secrets'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Copy-KeyVaultSecrets.ps1'
      ScriptArguments: '-SourceKeyVaultName $(primaryKeyVaultName) -DestinationKeyVaultName $(secondaryKeyVaultName) -ExcludeSecrets $(excludeSecretsFromCopy)'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Failover: Start App Services - Secondary'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Set-AppServiceState.ps1'
      ScriptArguments: '-ResourceGroupName $(secondaryResourceGroupName) -Action "Start"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Failover: Scale Down App Service Plans - Primary'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Invoke-ScaleAppServicePlan.ps1'
      ScriptArguments: '-ResourceGroupName $(primaryResourceGroupName) -Tier $(secondaryAppServicePlanTier) -WorkerSize "Small"'
      azurePowerShellVersion: LatestVersion