parameters:
  azureSubscription: ""

steps:
  - task: AzurePowerShell@5
    displayName: 'Stop App Services - $(geo) $(environment)'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Set-AppServiceState.ps1'
      ScriptArguments: '-ResourceGroupName ''$(resourceGroupName)'' -Action ''Stop'''
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Cleanup Key Vault - $(geo) $(environment)'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Remove-UnusedSecrets.ps1'
      ScriptArguments: '-KeyVaultName ''$(applicationKeyVaultName)'' -SecretsToKeep "$(validSecretList)".Split(",")'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Get DB Admin Password'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptType: FilePath
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/PipelineScripts/Set-SecretAsPipelineVariable.ps1'
      ScriptArguments: '-KeyVaultName ''$(deployKeyVaultName)'' -SecretName ''$(dbAdminPasswordSecretName)'' -VariableName ''dbAdminPassword'''
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Remove Navigator_User Sql User - $(geo) $(environment)'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Remove-SqlUser.ps1'
      ScriptArguments: '-SqlServerName ''$(SqlServerName)'' -UserName ''$(dbAdminLoginName)'' -UserPassword ''$(dbAdminPassword)'' -SqlUserToRemove ''Navigator_User'''
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Remove migration_account Sql User - $(geo) $(environment)'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Remove-SqlUser.ps1'
      ScriptArguments: '-SqlServerName ''$(SqlServerName)'' -UserName ''$(dbAdminLoginName)'' -UserPassword ''$(dbAdminPassword)'' -SqlUserToRemove ''migration_account'''
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Remove Api Key - $(geo) $(environment)'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Remove-AppInsightsApiKey'
      ScriptArguments: '-ResourceGroupName ''$(resourceGroupName)'' -AppInsightsName ''$(appInsightsName)'' -ApiKeyDescription ''Release Annotations'''
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@5
    displayName: 'Start App Services - $(geo) $(environment)'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Set-AppServiceState.ps1'
      ScriptArguments: '-ResourceGroupName ''$(resourceGroupName)'' -Action ''Start'''
      azurePowerShellVersion: LatestVersion