parameters:
  azureSubscription: ""
  deploySecondaryGeos: false

steps:
  - task: AzurePowerShell@5
    displayName: 'Create Resource Group - $(geo) - $(environmentFullName)'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptType: FilePath
      ScriptPath: '$(Pipeline.Workspace)/Infrastructure/Scripts/Add-ResourceGroup.ps1'
      ScriptArguments: '-ResourceGroupName ''$(resourceGroupName)'' -Location ''$(location)'''
      azurePowerShellVersion: LatestVersion

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: "Traffic Manager Resources Template - $(geo) - $(environmentFullName)"
    inputs:
      azureResourceManagerConnection: "${{ parameters.azureSubscription }}"
      subscriptionId: "$(subscriptionId)"
      resourceGroupName: "$(resourceGroupName)"
      location: "$(location)"
      csmFile: "$(Pipeline.Workspace)/Infrastructure/Templates/traffic-manager-template.json"
      csmParametersFile: "$(Pipeline.Workspace)/Infrastructure/Parameters/$(geo)/traffic-manager-parameters-$(locationCode)-$(environment).json"
      overrideParameters: -environmentIndex $(environmentIndex)

  - task: AzurePowerShell@5
    condition: and(succeeded(), not(in(variables['Environment'], 'bcp', 'test')),not(${{ parameters.deploySecondaryGeos }}))
    displayName: "Update Geo TM Target - $(geo) - $(environmentFullName)"
    inputs:
      azureSubscription: "${{ parameters.azureSubscription }}"
      ScriptType: FilePath
      ScriptPath: "$(Pipeline.Workspace)/Infrastructure/Scripts/Set-TrafficManagerEndpointTarget.ps1"
      ScriptArguments: '-ResourceGroupName "$(resourceGroupName)" -TrafficManagerName "$(geoTrafficManagerName)" -EndpointName "$(primaryEndpoint)" -EndpointTarget "$(primaryEndpointTarget)"'
      azurePowerShellVersion: LatestVersion