trigger: none

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  environmentIndex: "1"

stages:
- stage: BUILD
  jobs:
    - template: build-templates/infrastructure-build-jobs-template.yml

- stage: AME_DEV_${{ variables.environmentIndex }}
  dependsOn: BUILD
  variables:
  - template: variables-templates/dev-variables-template.yml
    parameters:
      environmentIndex: ${{ variables.environmentIndex }}
  jobs:
    - deployment: AME_DEV
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PREPROD
        geo: ame
        lifecycle: npd
        environment: dev
        environmentIndex: ${{ variables.environmentIndex }}

- stage: AME_QA_${{ variables.environmentIndex }}
  dependsOn: AME_DEV_${{ variables.environmentIndex }}
  variables:
  - template: variables-templates/qa-variables-template.yml
    parameters:
      environmentIndex: ${{ variables.environmentIndex }}
  jobs:
    - deployment: AME_QA
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PREPROD
        geo: ame
        lifecycle: npd
        environment: qa
        environmentIndex: ${{ variables.environmentIndex }}

- stage: AME_LOAD
  dependsOn: AME_QA_${{ variables.environmentIndex }}
  variables:
  - template: variables-templates/load-variables-template.yml
  jobs:
    - deployment: AME_LOAD
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USE2-NPD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PREPROD
        geo: ame
        lifecycle: npd
        environment: load

- stage: AME_STAGE
  dependsOn: AME_LOAD
  variables:
  - template: variables-templates/stage-variables-template.yml
  jobs:
    - deployment: AME_STAGE
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PROD
        geo: ame
        lifecycle: stg
        environment: stage

- stage: AME_PROD
  dependsOn: AME_STAGE
  variables:
  - template: variables-templates/prod-variables-template.yml
  jobs:
    - deployment: AME_PROD
      environment: INFRASTRUCTURE_PROD_AME
      pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PROD
        geo: ame
        lifecycle: prod
        environment: prod

- stage: AME_BCP
  dependsOn: AME_PROD
  variables:
  - template: variables-templates/bcp-variables-template.yml
  jobs:
    - deployment: AME_BCP
      environment: INFRASTRUCTURE_PROD_AME
      pool: ASSURANCE-USC-BCP-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USC-BCP-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PROD 
        geo: ame
        lifecycle: bcp
        environment: bcp

- stage: EMA_DEV_${{ variables.environmentIndex }}
  dependsOn: BUILD
  variables:
  - template: variables-templates/dev-variables-template.yml
    parameters:
      environmentIndex: ${{ variables.environmentIndex }}
  jobs:
    - deployment: EMA_DEV
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PREPROD
        geo: ema
        lifecycle: npd
        environment: dev
        isPrimaryGeo: true
        environmentIndex: ${{ variables.environmentIndex }}

- stage: EMA_QA_${{ variables.environmentIndex }}
  dependsOn: EMA_DEV_${{ variables.environmentIndex }}
  variables:
  - template: variables-templates/qa-variables-template.yml
    parameters:
      environmentIndex: ${{ variables.environmentIndex }}
  jobs:
    - deployment: EMA_QA
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PREPROD
        geo: ema
        lifecycle: npd
        environment: qa
        isPrimaryGeo: true
        environmentIndex: ${{ variables.environmentIndex }}

- stage: EMA_LOAD
  dependsOn: EMA_QA_${{ variables.environmentIndex }}
  variables:
  - template: variables-templates/load-variables-template.yml
  jobs:
    - deployment: EMA_LOAD
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUW-NPD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PREPROD
        geo: ema
        lifecycle: npd
        environment: load
        isPrimaryGeo: true

- stage: EMA_STAGE
  dependsOn: EMA_LOAD
  variables:
  - template: variables-templates/stage-variables-template.yml
  jobs:
    - deployment: EMA_STAGE
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PROD
        geo: ema
        lifecycle: stg
        environment: stage
        isPrimaryGeo: true

- stage: EMA_PROD
  dependsOn: EMA_STAGE
  variables:
  - template: variables-templates/prod-variables-template.yml
  jobs:
    - deployment: EMA_PROD
      environment: INFRASTRUCTURE_PROD_EMA
      pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PROD
        geo: ema
        lifecycle: prod
        environment: prod
        isPrimaryGeo: true

- stage: EMA_BCP
  dependsOn: EMA_PROD
  variables:
  - template: variables-templates/bcp-variables-template.yml
  jobs:
    - deployment: EMA_BCP
      environment: INFRASTRUCTURE_PROD_EMA
      pool: ASSURANCE-EUN-BCP-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUN-BCP-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PROD
        geo: ema
        lifecycle: bcp
        environment: bcp
        isPrimaryGeo: true

- stage: APA_DEV_${{ variables.environmentIndex }}
  dependsOn: BUILD
  variables:
  - template: variables-templates/dev-variables-template.yml
    parameters:
      environmentIndex: ${{ variables.environmentIndex }}
  jobs:
    - deployment: APA_DEV
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PREPROD
        geo: apa
        lifecycle: npd
        environment: dev
        environmentIndex: ${{ variables.environmentIndex }}

- stage: APA_QA_${{ variables.environmentIndex }}
  dependsOn: APA_DEV_${{ variables.environmentIndex }}
  variables:
  - template: variables-templates/qa-variables-template.yml
    parameters:
      environmentIndex: ${{ variables.environmentIndex }}
  jobs:
    - deployment: APA_QA
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PREPROD
        geo: apa
        lifecycle: npd
        environment: qa
        environmentIndex: ${{ variables.environmentIndex }}

- stage: APA_LOAD
  dependsOn: APA_QA_${{ variables.environmentIndex }}
  variables:
  - template: variables-templates/load-variables-template.yml
  jobs:
    - deployment: APA_LOAD
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPE-NPD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PREPROD
        geo: apa
        lifecycle: npd
        environment: load

- stage: APA_STAGE
  dependsOn: APA_LOAD
  variables:
  - template: variables-templates/stage-variables-template.yml
  jobs:
    - deployment: APA_STAGE
      environment: INFRASTRUCTURE_NPD
      pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PROD
        geo: apa
        lifecycle: stg
        environment: stage

- stage: APA_PROD
  dependsOn: APA_STAGE
  variables:
  - template: variables-templates/prod-variables-template.yml
  jobs:
    - deployment: APA_PROD
      environment: INFRASTRUCTURE_PROD_APA
      pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PROD
        geo: apa
        lifecycle: prod
        environment: prod

- stage: APA_BCP
  dependsOn: APA_PROD
  variables:
  - template: variables-templates/bcp-variables-template.yml
  jobs:
    - deployment: APA_BCP
      environment: INFRASTRUCTURE_PROD_APA
      pool: ASSURANCE-JPW-BCP-AKS-WIN-RELEASE
    - template: deployment-templates/clean-up-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPW-BCP-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PROD
        geo: apa
        lifecycle: bcp
        environment: bcp
