trigger: none

name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: BUILD
  jobs:
    - template: build-templates/infrastructure-build-jobs-template.yml

- stage: AME_INT
  dependsOn: BUILD
  jobs:
    - deployment: AME_INT
      environment: INFRASTRUCTURE_PROD_TEST
      pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
    - template: deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USE2-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PROD
        geo: ame
        lifecycle: prod
        environment: int
        infrastructurePipelineAlias: Infrastructure

- stage: AME_TEST
  dependsOn: AME_INT
  jobs:
    - deployment: AME_TEST
      environment: INFRASTRUCTURE_PROD_TEST
      pool: ASSURANCE-USC-BCP-AKS-WIN-RELEASE
    - template: deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-USC-BCP-AKS-WIN-RELEASE
        azureSubscription: AzureRM_US_AUDIT_PROD
        geo: ame
        lifecycle: bcp
        environment: test
        infrastructurePipelineAlias: Infrastructure

- stage: EMA_INT
  dependsOn: BUILD
  jobs:
    - deployment: EMA_INT
      environment: INFRASTRUCTURE_PROD_TEST
      pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
    - template: deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUW-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PROD
        geo: ema
        lifecycle: prod
        environment: int
        isPrimaryGeo: true
        infrastructurePipelineAlias: Infrastructure

- stage: EMA_TEST
  dependsOn: EMA_INT
  jobs:
    - deployment: EMA_TEST
      environment: INFRASTRUCTURE_PROD_TEST
      pool: ASSURANCE-EUN-BCP-AKS-WIN-RELEASE
    - template: deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-EUN-BCP-AKS-WIN-RELEASE
        azureSubscription: AzureRM_EMA_AUDIT_PROD
        geo: ema
        lifecycle: bcp
        environment: test
        isPrimaryGeo: true
        infrastructurePipelineAlias: Infrastructure

- stage: APA_INT
  dependsOn: BUILD
  jobs:
    - deployment: APA_INT
      environment: INFRASTRUCTURE_PROD_TEST
      pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
    - template: deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPE-PROD-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PROD
        geo: apa
        lifecycle: prod
        environment: int
        infrastructurePipelineAlias: Infrastructure

- stage: APA_TEST
  dependsOn: APA_INT
  jobs:
    - deployment: APA_TEST
      environment: INFRASTRUCTURE_PROD_TEST
      pool: ASSURANCE-JPW-BCP-AKS-WIN-RELEASE
    - template: deployment-templates/rotate-secrets-deployment-jobs-template.yml
      parameters:
        pool: ASSURANCE-JPW-BCP-AKS-WIN-RELEASE
        azureSubscription: AzureRM_APA_AUDIT_PROD
        geo: apa
        lifecycle: bcp
        environment: test
        infrastructurePipelineAlias: Infrastructure
