trigger: none

name: $(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: deploymentChannel
    displayName: Deployment channel 
    type: string
    default: Hotfix Testing
    values:
      - Hotfix Testing
      - Hotfix Release
  - name: storeSQLUser
    displayName: Store SQL Developer Accounts (Lower Envs)
    type: boolean
    default: false

variables:
  environmentIndex: "h"

stages:
  - stage: BUILD
    jobs:
      - template: build-templates/infrastructure-build-jobs-template.yml

  - ${{ if eq(parameters.deploymentChannel, 'Hotfix Testing') }}:
    - template: stage-templates/rotate-secrets-feature-stage-template.yml
      parameters:
        environmentIndex: ${{ variables.environmentIndex }}
        storeSQLUser: ${{ parameters.storeSQLUser }}

  - ${{ if eq(parameters.deploymentChannel, 'Hotfix Release') }}:
    - template: stage-templates/rotate-secrets-hotfix-stage-template.yml
