trigger: none

name: $(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: deploymentChannel
    displayName: Deployment channel 
    type: string
    default: Feature Release
    values:
      - Feature Testing
      - Feature Release
  - name: storeSQLUser
    displayName: Store SQL Developer Accounts (Lower Envs)
    type: boolean
    default: false

variables:
  environmentIndex: "1"
  pipelineId: 8398 #Pipeline ID to specify the unique pipeline that can deploy Infrastructure to LOAD and PROD environments.

stages:
  - stage: BUILD
    jobs:
      - template: build-templates/infrastructure-build-jobs-template.yml

  - ${{ if and(eq(parameters.deploymentChannel, 'Feature Testing'), ne(variables['System.DefinitionId'], variables.pipelineId)) }}:
    - template: stage-templates/rotate-secrets-feature-stage-template.yml
      parameters:
        environmentIndex: ${{ variables.environmentIndex }}
        storeSQLUser: ${{ parameters.storeSQLUser }}

  - ${{ if and(eq(parameters.deploymentChannel, 'Feature Release'), eq(variables['System.DefinitionId'], variables.pipelineId)) }}:
    - template: stage-templates/rotate-secrets-release-stage-template.yml
      parameters:
        storeSQLUser: ${{ parameters.storeSQLUser }}