trigger: none

name: $(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: CER_QandA
      type: git
      name: CER_QandA
      ref: refs/heads/develop

variables:
  buildConfiguration: "Debug"
  dotNetVersion: "8.x"
  projectKey: "Navigator_QandA"
  solutionFileName: "CER_QandA.sln"

stages:
- stage: SONARQUBE_SCAN
  jobs:
  - job: SONARQUBE_SCAN
    pool: 
      vmImage: 'windows-latest'
    variables:
      - template: variables-templates/build-variables-template.yml

    steps:
    - checkout: CER_QandA
      clean: true

    - checkout: self
      clean: true
    
    - task: PowerShell@2
      displayName: 'Display Variables'
      inputs:
        targetType: inline
        script: |
          Get-ChildItem -Path env: | Where-Object { $_.Name -notmatch '(AGENT_.*|AZURE_.*|RELEASE_.*|SYSTEM_.*)' } | Format-Table -AutoSize

    - task: UseDotNet@2
      displayName: "Use .Net Core sdk ${{ variables.dotNetVersion }}"
      inputs:
       version: ${{ variables.dotNetVersion }}

    - task: DotNetCoreCLI@2
      displayName: "dotnet restore: ${{ variables.solutionFileName }}"
      inputs:
        command: restore
        projects: "**/${{ variables.solutionFileName }}"
        vstsFeed: "$(vstsFeed)"

    - task: SonarQubePrepare@6
      displayName: 'Prepare analysis on SonarQube'
      inputs:
        SonarQube: 'SonarQube'
        projectKey: ${{ variables.projectKey }}
        projectName: ${{ variables.projectKey }}
        projectVersion: '$(Build.buildnumber)'

    - task: DotNetCoreCLI@2
      displayName: "dotnet build: ${{ variables.solutionFileName }}"
      inputs:
        projects: "**/${{ variables.solutionFileName }}"
        arguments: "-c $(buildConfiguration) --no-restore"

    - task: SonarQubeAnalyze@6
      displayName: 'Run Code Analysis'
      inputs: 
        jdkversion: 'JAVA_HOME_21_X64'

    - task: SonarQubePublish@6
      displayName: 'Publish Quality Gate Result'