trigger: none

name: $(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: deploymentChannel
    displayName: Deployment channel
    type: string
    default: Hotfix Testing
    values:
      - Hotfix Testing
      - Hotfix Release

variables:
  environmentIndex: "h"
  artifactName: "navigatorUi"

resources:
  repositories:
    - repository: CER_App
      type: git
      name: CER_APP
      ref: refs/heads/develop

stages:
  - stage: BUILD
    jobs:
      - template: build-templates/ui-build-jobs-template.yml
        parameters:
          pool: 
            vmImage: 'windows-latest'
          azureSubscription: AzureRM_US_AUDIT_PREPROD
          reactProjects:
            - job: UiBuild
              pool: 
                vmImage: 'windows-latest'
              variables:
                repositoryName: CER_App
                projectName: Deloitte.Assurance.CER.UI
                artifactName: ${{ variables.artifactName }}
                # Required due to version conflict between Navigator and React eslint versions.
                # This disables eslint so the build doesn't fail.
                DISABLE_ESLINT_PLUGIN: true

  - ${{ if eq(parameters.deploymentChannel, 'Hotfix Testing') }}:
      - template: stage-templates/ui-feature-stage-template.yml
        parameters:
          environmentIndex: ${{ variables.environmentIndex }}
          webAppServices:
            navigatorUi:
              artifactName: ${{ variables.artifactName }}
              resourceName: ui
              packageName: Deloitte.Assurance.CER.UI.zip

  - ${{ if eq(parameters.deploymentChannel, 'Hotfix Release') }}:
      - template: stage-templates/ui-hotfix-stage-template.yml
        parameters:
          webAppServices:
            navigatorUi:
              artifactName: ${{ variables.artifactName }}
              resourceName: ui
              packageName: Deloitte.Assurance.CER.UI.zip
