parameters:
  buildConfiguration: ""
  vstsFeed: ""
  dotnetCoreProjects: []

jobs:
  - template: infrastructure-build-jobs-template.yml

  - ${{ each job in parameters.dotnetCoreProjects }}:
      - ${{ each pair in job }}:
          ${{ if ne(pair.key, 'steps') }}:
            ${{ pair.key }}: ${{ pair.value }}
        steps:
          - template: steps-templates/dot-net-core-build-steps-template.yml
            parameters:
              artifactName: "${{ job.variables.artifactName }}"
              projectName: "${{ job.variables.projectName }}"
              repositoryName: "${{ job.variables.repositoryName }}"
              buildConfiguration: ${{ parameters.buildConfiguration }}
              vstsFeed: ${{ parameters.vstsFeed }}
