parameters:
  vstsFeed: ""
  buildConfiguration: "" 
  dotnetCoreProjects: []

jobs:
  - template: infrastructure-build-jobs-template.yml

  - ${{ each job in parameters.dotnetCoreProjects }}:
    - ${{ each pair in job }}:
        ${{ if ne(pair.key, 'steps') }}:
          ${{ pair.key }}: ${{ pair.value }}
      steps:
        - template: steps-templates/dot-net-core-build-steps-template.yml 
          parameters:
            repositoryName: "${{ job.variables.repositoryName }}"
            projectName: "${{ job.variables.projectName }}"
            artifactName: "${{ job.variables.artifactName }}"
            buildConfiguration: "${{ parameters.buildConfiguration }}"
            vstsFeed: "${{ parameters.vstsFeed }}"