parameters:
  pool: null
  azureSubscription: ""
  geo: ""
  lifecycle: ""
  environment: ""
  isPrimaryGeo: false

jobs:
  - job: ${{ parameters.geo }}_${{ parameters.environment }}_BCP_FAILOVER
    pool: ${{ parameters.pool }}
    variables:
      - template: ../variables-templates/${{ parameters.environment}}-variables-template.yml
      - template: ../variables-templates/${{ parameters.lifecycle }}-${{ parameters.geo}}-variables-template.yml
      - template: ../variables-templates/${{ parameters.geo}}-variables-template.yml
      - template: ../variables-templates/release-variables-template.yml
        parameters:
          environment: ${{ parameters.environment }}
          isPrimaryGeo: ${{ parameters.isPrimaryGeo }}
      - template: ../variables-templates/failover-variables-template.yml
    steps:
      - checkout: none
      - download: current

      - template: steps-templates/bcp-failover-deployment-steps-template.yml
        parameters:
          azureSubscription: ${{ parameters.azureSubscription }}
