parameters:
  pool: null
  azureSubscription: ""
  geo: ""
  lifecycle: ""
  environment: ""
  environmentIndex: ""
  isPrimaryGeo: false

jobs:
  - job: CleanUpSecretsDeployment
    workspace:
      clean: all
    pool: ${{ parameters.pool }}
    variables:
      - template: ../variables-templates/${{ parameters.environment}}-variables-template.yml
        parameters:
          environmentIndex: ${{ parameters.environmentIndex }}
      - template: ../variables-templates/${{ parameters.lifecycle }}-${{ parameters.geo}}-variables-template.yml
      - template: ../variables-templates/${{ parameters.geo}}-variables-template.yml
      - template: ../variables-templates/release-variables-template.yml
        parameters:
          environment: ${{ parameters.environment }}
          isPrimaryGeo: ${{ parameters.isPrimaryGeo }}
    steps:
      - checkout: none
      - download: current

      - template: steps-templates/pipeline-generate-variables-steps-template.yml

      - ${{ if or(eq(parameters.isPrimaryGeo, true), eq(variables.deploySecondaryGeos, true)) }}:
        - template: steps-templates/clean-up-secrets-deployment-steps-template.yml
          parameters:
            azureSubscription: "${{ parameters.azureSubscription }}"
