parameters:
  pool: null
  azureSubscription: ""
  geo: ""
  lifecycle: ""
  environment: ""
  dependsOn: ""
  isPrimaryGeo: false
  endpointName: ""

jobs:
  - job: MaintenancePageShowHide
    ${{ if length(parameters.dependsOn) }}:
      dependsOn: ${{ parameters.dependsOn }}
    pool: ${{ parameters.pool }}
    variables:
      - template: ../variables-templates/${{ parameters.environment}}-variables-template.yml
      - template: ../variables-templates/${{ parameters.lifecycle }}-${{ parameters.geo}}-variables-template.yml
      - template: ../variables-templates/${{ parameters.geo}}-variables-template.yml
      - template: ../variables-templates/release-variables-template.yml
        parameters:
          environment: ${{ parameters.environment }}
          isPrimaryGeo: ${{ parameters.isPrimaryGeo }}
    steps:
      - checkout: none
      - download: current
      
      - task: PowerShell@2
        displayName: "Display Variables"
        inputs:
          targetType: inline
          script: |
            Get-ChildItem -Path env: | Where-Object { $_.Name -notmatch '(AGENT_.*|AZURE_.*|BUILD_.*|RELEASE_.*|SYSTEM_.*)' } | Format-Table -AutoSize

      - task: AzurePowerShell@5
        displayName: 'Enable Traffic Manager Profile - $(geoTrafficManagerName)\${{ parameters.endpointName }}'
        inputs:
          azureSubscription: "${{ parameters.azureSubscription }}"
          ScriptPath: "$(Pipeline.Workspace)/Infrastructure/Scripts/Set-TrafficManagerEndpointStatus.ps1"
          ScriptArguments: -ResourceGroupName '$(primaryResourceGroupName)' -TrafficManagerName '$(geoTrafficManagerName)' -EndpointName '${{ parameters.endpointName }}'
          azurePowerShellVersion: LatestVersion
