variables:
  appDbNames: Navigator_Case_Master
  containerInstanceCodes: 'AU,GU,HK,ID,IN,JP,KH,KR,LA,MM,MU,MY,NZ,PG,PH,SG,TH,TW,VN'
  deployKeyVaultName: fincalcapaprddeployvault
  geo: 'apa'
  lifecycle: 'prod'
  lifecycleAlias: 'p'
  location: 'japaneast'
  locationCode: 'jpe'
  subscriptionId: 'b2fcc9cc-5757-42d3-980c-d92d66bab682'
  primaryEndpointTarget: 'audit-shared-prd.westeurope.cloudapp.azure.com'