parameters:
  - name: environmentIndex
    type: string
    default: ""
  - name: geo
    type: string
    default: ""

variables:
  developerDatabaseRoles:
  deploySecondaryGeos: true
  environment: prod
  environmentIndex: ${{ parameters.environmentIndex }}
  environmentAlias: p$(environmentIndex)
  primaryEnvironmentAlias: "p"
  primaryEnvironmentName: "prod"
  secondaryEnvironmentAlias: "b"
  secondaryEnvironmentName: "bcp"
  functionAppNames: "QnA"

  ${{ if in(parameters.geo, 'ame') }}:
    deloitteInternalSubnetId: "/subscriptions/8c71ef53-4473-4862-af36-bae6e40451b2/resourceGroups/AUDIT_PROD_RG_Network/providers/Microsoft.Network/virtualNetworks/azeus2prdvnt01/subnets/AUDIT_PROD_PRIVATE_ENDPOINT_Subnet"
  ${{ if in(parameters.geo, 'apa') }}:
    deloitteInternalSubnetId: "/subscriptions/b2fcc9cc-5757-42d3-980c-d92d66bab682/resourceGroups/AZRG-JPE-AUD-ITS-PRD/providers/Microsoft.Network/virtualNetworks/AZAPAJPEAUDPRDVNT01/subnets/AUDIT_PROD_PRIVATE_ENDPOINT_SUBNET"
  ${{ if in(parameters.geo, 'ema') }}:
    deloitteInternalSubnetId: "/subscriptions/62c1dd5c-d918-4a4d-b0ee-18d5e7d5071b/resourceGroups/AZRG-EUN-AUD-ITS-PRD/providers/Microsoft.Network/virtualNetworks/azeuwprdvnt01/subnets/AUDIT_PROD_PRIVATE_ENDPOINT_Subnet"
